services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "1"
    command: flask run -h 0.0.0.0
  db:
    image: postgres
    environment:
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bd-users
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "userdb", "-d", "bd-users"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db_data:
